### ISSUE TITLE
Sidebar separator blocking the scrollbar

### ISSUE THREAD

**Issue by Buca** [Tonejs/tonejs.github.io#16]
The sidebar separator seems to be blocking the mouse events on the scrollbar, i.e. I can't click on the sidebar when the mouse is positioned on the center of the scroll. 

There's two possible fixes for this, either add `pointer-events: none` to the separator class ( which is spelled "seperator" in the CSS file ) or do some `z-index` magic, which only works with elements that are positioned: `position: absolute/relative/fixed/sticky`, but that would also mean adding z-index and position attributes to the sidebar, also this would ( probably ) put the separator underneath the sidebar, and in so making it invisible.

 I would recommend going with the `pointer-events: none` since it produces no unwanted side-effects and is simple to add.

The CSS file and specific line and css class/id I'm speaking of can be found [here](https://github.com/Tonejs/tonejs.github.io/blob/master/assets/css/sidebar.scss#L29).

**Comment by eliraybon** [comment]
I fixed this issue, following Buca's recommendation to add `pointer-events: none` to the separator class. Made pull request.

**Comment by tambien** [comment]
Thanks for the PR @eliraybon could you tell me if this is still an issue on the 'next' version of the documentation: https://tonejs.github.io/docs/14.5.40/Gain

**Comment by eliraybon** [comment]
@tambien Everything is good on that version!

**Comment by Buca** [comment]
I can confirm that it isn't an issue on 'next' version of the docs. I will be closing the issue now.
Thank you @eliraybon and @tambien.
