### ISSUE TITLE
Typo in the example of Tone.FrequencyEnvelope

### ISSUE THREAD

**Issue by vibertthio** [Tonejs/tonejs.github.io#5]
[Tone.FrequencyEnvelope](https://tonejs.github.io/docs/r11/FrequencyEnvelope)

<img width="357" alt="screen shot 2017-12-31 at 1 35 51 am" src="https://user-images.githubusercontent.com/19225067/34456167-028d447a-edcb-11e7-9590-67bda84b78ef.png">

It should be like:
```javascript
var env = new Tone.FrequencyEnvelope({
 	"attack" : 0.2,
 	"baseFrequency" : "C2",
 	"octaves" : 4
 });
 env.connect(oscillator.frequency);
```

**Comment by tambien** [comment]
fixed in the Tone.js codebase.
