### ISSUE TITLE
Keyboard library?

### ISSUE THREAD

**Issue by sonph** [Tonejs/tonejs.github.io#8]
What's the library you used for the keyboard in `simpleSynth.html`? Can only find the minified `Keyboard.js` file :) Thanks!

**Comment by sonph** [comment]
Ping @tambien

**Comment by tambien** [comment]
@sonph Pretty sure i built that file from [this code](https://github.com/googlecreativelab/aiexperiments-ai-duet/blob/master/static/src/keyboard/Keyboard.js). Since that's not really a supported library, i'm planning on moving most of the examples to [nexus-ui](https://nexus-js.github.io/ui/)
